Repository ImpulsoGov/coronacidades-datasource, pull requests merged in 2020-10, with the labels that each got.

#100 Missing dictionaries added.
  dictionaries/README.md
  dictionaries/br_cities_cases_full.csv
  dictionaries/br_cnae_sectors.csv
  dictionaries/br_health_region_cases_full.csv
  dictionaries/br_health_region_rt.csv
  dictionaries/br_health_region_safereopen_main.csv
  dictionaries/br_maps.csv
  dictionaries/br_states_cases_full.csv
Labels: documentation

#101 Add safeschool endpoints
  src/loader/endpoints.yaml
  src/loader/endpoints/get_cities_safeschools_main.py
  src/loader/endpoints/get_cities_safeschools_students.py
Labels: new data

#103 Fix states cases
  loader.dockerfile
  src/loader/endpoints/get_cities_cases.py
  src/loader/endpoints/get_states_cases.py
Labels: corrections, enhancement

#104 Fix states cases
  loader.dockerfile
  src/loader/endpoints/get_cities_cases.py
  src/loader/endpoints/get_states_cases.py
Labels: corrections, enhancement

#106 Add SafeSchool endpoint tests + Update w/ state level
  src/loader/endpoints.yaml
  src/loader/endpoints/get_cities_safeschools_main.py
Labels: corrections, enhancement
